name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: go_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.21

      - name: Build Docker containers
        run: docker compose build

      - name: Start containers
        run: docker compose up -d

      - name: Wait for app to start
        run: sleep 10

      - name: Run tests inside app container
        run: |
          CONTAINER_ID=$(docker ps -qf "ancestor=http-server-go_app")
          docker exec $CONTAINER_ID go test ./tests/...


